<?php
if(session_status()===PHP_SESSION_NONE)session_start();
require_once __DIR__.'/config/conexao.php'; require_once __DIR__.'/auth/verifica_login.php';
function h($v){return htmlspecialchars((string)$v,ENT_QUOTES,'UTF-8');}
$fornecedores=$pdo->query("SELECT id,COALESCE(NULLIF(nome_fantasia,''),razao_social) nome FROM fornecedores WHERE status='ATIVO' ORDER BY nome")->fetchAll();
$produtos=$pdo->query("SELECT p.id,p.codigo,p.sku,p.nome,'Produto para Venda' tipo,COALESCE(NULLIF(f.nome_fantasia,''),f.razao_social) fornecedor FROM produtos p LEFT JOIN fornecedores f ON f.id=p.fornecedor_id WHERE p.status='ATIVO' ORDER BY p.nome LIMIT 50")->fetchAll();
$suprimentos=$pdo->query("SELECT s.id,s.codigo,s.nome,'Material de Uso' tipo,COALESCE(NULLIF(f.nome_fantasia,''),f.razao_social) fornecedor FROM suprimentos s LEFT JOIN fornecedor_suprimentos fs ON fs.suprimento_id=s.id AND fs.fornecedor_preferencial=1 LEFT JOIN fornecedores f ON f.id=fs.fornecedor_id WHERE s.status='ATIVO' ORDER BY s.nome LIMIT 50")->fetchAll();
$msg=$_SESSION['itens_msg']??'';$tipo=$_SESSION['itens_tipo']??'sucesso';unset($_SESSION['itens_msg'],$_SESSION['itens_tipo']);
require_once __DIR__.'/includes/header.php'; require_once __DIR__.'/includes/sidebar.php';
?>
<div class="main"><div class="topbar"><div><h1>Cadastro de Itens</h1><p>Uma única tela para Produto para Venda e Material de Uso.</p></div></div><div class="content"><div class="suprimentos-container">
<?php if($msg): ?><div class="suprimentos-message <?=h($tipo)?>"><?=h($msg)?></div><?php endif; ?>
<div class="suprimentos-form-box"><h2>Novo item</h2><p class="form-help">Selecione o tipo. O sistema mostra somente os campos necessários para aquela finalidade.</p>
<form method="post" action="controllers/itens_controller.php" id="form-item"><input type="hidden" name="acao" value="salvar_item">
<div class="suprimentos-form-grid">
<div class="full"><label>Tipo de item *</label><select name="tipo_item" id="tipo_item" required><option value="">Selecione</option><option value="PRODUTO">Produto para Venda</option><option value="MATERIAL">Material de Uso</option></select></div>
<div class="full"><label>Fornecedor *</label><select name="fornecedor_id" required><option value="">Selecione um fornecedor cadastrado</option><?php foreach($fornecedores as $f): ?><option value="<?=$f['id']?>"><?=h($f['nome'])?></option><?php endforeach; ?></select><small class="form-help">Cadastre fornecedores em Fornecedores.</small></div>
<div><label>Código</label><input name="codigo" placeholder="Ex.: SKU/INS-001"></div><div><label>Nome *</label><input name="nome" required></div><div><label>Unidade *</label><select name="unidade_medida"><option>UN</option><option>KG</option><option>G</option><option>M</option><option>M2</option><option>L</option><option>CX</option><option>PCT</option><option>ROLO</option></select></div>
<div id="produto-campos" class="full" style="display:none"><div class="suprimentos-form-grid"><div><label>SKU</label><input name="sku"></div><div><label>Valor pago</label><input type="number" step="0.01" min="0" name="preco_custo" value="0"></div><div><label>Preço de venda</label><input type="number" step="0.01" min="0" name="preco_venda" value="0"></div><div><label>Estoque mínimo local</label><input type="number" step="0.01" min="0" name="estoque_minimo_local" value="0"></div><div><label>Estoque mínimo Mercado Livre</label><input type="number" step="0.01" min="0" name="estoque_minimo_mercado_livre" value="0"></div><div><label>Estoque local inicial</label><input type="number" step="0.01" min="0" name="estoque_local_inicial" value="0"></div><div><label>Estoque ML inicial</label><input type="number" step="0.01" min="0" name="estoque_ml_inicial" value="0"></div></div></div>
<div id="material-campos" class="full" style="display:none"><div class="suprimentos-form-grid"><div><label>Estoque atual</label><input type="number" step="0.01" min="0" name="estoque_atual" value="0"></div><div><label>Estoque mínimo</label><input type="number" step="0.01" min="0" name="estoque_minimo" value="0"></div></div></div>
</div><button class="btn btn-pri">Cadastrar item</button></form></div>
<div class="card"><div class="section-header"><div><h2>Últimos itens cadastrados</h2><p>Produtos e materiais passam a compartilhar a mesma entrada de cadastro.</p></div></div><div class="suprimentos-table-wrap"><table class="suprimentos-table"><thead><tr><th>Tipo</th><th>Item</th><th>Fornecedor</th><th>Identificação</th></tr></thead><tbody><?php foreach(array_merge($produtos,$suprimentos) as $i): ?><tr><td><span class="estoque-tag <?=strpos($i['tipo'],'Produto')!==false?'ok':'atencao'?>"><?=h($i['tipo'])?></span></td><td><strong><?=h($i['nome'])?></strong></td><td><?=h($i['fornecedor']??'—')?></td><td><?=h($i['codigo']??'—')?><?=!empty($i['sku'])?' · SKU '.h($i['sku']):''?></td></tr><?php endforeach; ?></tbody></table></div></div>
</div></div></div>
<script>document.addEventListener('DOMContentLoaded',function(){const t=document.getElementById('tipo_item'),p=document.getElementById('produto-campos'),m=document.getElementById('material-campos');function a(){const produto=t.value==='PRODUTO';p.style.display=produto?'block':'none';m.style.display=produto||!t.value?'none':'block';p.querySelectorAll('input').forEach(x=>x.disabled=!produto);m.querySelectorAll('input').forEach(x=>x.disabled=produto||!t.value);}t.addEventListener('change',a);a();});</script>
<?php require_once __DIR__.'/includes/footer.php'; ?>
