<?php
if(session_status()===PHP_SESSION_NONE)session_start();require_once __DIR__.'/config/conexao.php';require_once __DIR__.'/auth/verifica_login.php';
function h($v){return htmlspecialchars((string)$v,ENT_QUOTES,'UTF-8');}function nf($v){return number_format((float)$v,2,',','.');}
$estoque=$pdo->query("SELECT p.codigo,p.nome,p.estoque_minimo,p.estoque_seguranca,p.ponto_reposicao,COALESCE(SUM(CASE WHEN e.local_estoque='FISICO' THEN e.quantidade ELSE 0 END),0) fisico,COALESCE(SUM(CASE WHEN e.local_estoque='MERCADO_LIVRE' THEN e.quantidade ELSE 0 END),0) ml FROM produtos p LEFT JOIN estoque e ON e.produto_id=p.id WHERE p.status='ATIVO' GROUP BY p.id ORDER BY p.nome")->fetchAll();
$entradas=$pdo->query("SELECT p.nome,COALESCE(SUM(CASE WHEN m.tipo IN ('ENTRADA_COMPRA','AJUSTE_ENTRADA','DEVOLUCAO') THEN m.quantidade ELSE 0 END),0) entradas,COALESCE(SUM(CASE WHEN m.tipo IN ('SAIDA_VENDA','PERDA','AVARIA','AJUSTE_SAIDA') THEN m.quantidade ELSE 0 END),0) saidas FROM produtos p LEFT JOIN movimentacoes_estoque m ON m.produto_id=p.id AND m.local_estoque='FISICO' GROUP BY p.id ORDER BY p.nome")->fetchAll();
$precos=$pdo->query("SELECT s.nome,f.nome_fantasia,fs.preco_unitario,fs.prazo_entrega_dias FROM fornecedor_suprimentos fs JOIN suprimentos s ON s.id=fs.suprimento_id JOIN fornecedores f ON f.id=fs.fornecedor_id WHERE fs.preco_unitario IS NOT NULL ORDER BY s.nome,fs.preco_unitario")->fetchAll();
$consumo=$pdo->query("SELECT s.nome,s.unidade_medida,COALESCE(SUM(CASE WHEN m.tipo='CONSUMO' THEN m.quantidade ELSE 0 END),0) consumo FROM suprimentos s LEFT JOIN movimentacoes_suprimentos m ON m.suprimento_id=s.id AND m.created_at>=DATE_SUB(NOW(),INTERVAL 30 DAY) GROUP BY s.id ORDER BY consumo DESC")->fetchAll();
require_once __DIR__.'/includes/header.php';require_once __DIR__.'/includes/sidebar.php';
?>
<div class="main"><div class="topbar"><div><h1>Relatórios e análise</h1><p>Informações para conferência de estoque e apoio à decisão de compras.</p></div></div><div class="content"><div class="suprimentos-container">
<div class="suprimentos-info"><strong>Como usar:</strong> os relatórios mostram o que está acontecendo com o estoque. Os parâmetros de mínimo, segurança e reposição servem como apoio; a decisão de compra continua com o responsável.</div>
<div class="card"><div class="section-header"><div><h2>Estoque atual e cobertura de reposição</h2><p>Visão por produto, incluindo o saldo no Mercado Livre.</p></div></div><div class="suprimentos-table-wrap"><table class="suprimentos-table"><thead><tr><th>Produto</th><th>Físico</th><th>Mercado Livre</th><th>Mínimo</th><th>Segurança</th><th>Ponto de reposição</th><th>Situação</th></tr></thead><tbody><?php foreach($estoque as $e):$disp=(float)$e['fisico'];$rep=(float)$e['ponto_reposicao'];$sit=$disp<=0?'RUPTURA':($disp<=(float)$e['estoque_minimo']?'ABAIXO DO MÍNIMO':($disp<=$rep?'REPOR':'NORMAL'));?><tr><td><strong><?=h($e['nome'])?></strong><small><?=h($e['codigo'])?></small></td><td><?=nf($e['fisico'])?></td><td><?=nf($e['ml'])?></td><td><?=nf($e['estoque_minimo'])?></td><td><?=nf($e['estoque_seguranca'])?></td><td><?=nf($e['ponto_reposicao'])?></td><td><?=h($sit)?></td></tr><?php endforeach;?></tbody></table></div></div>
<div class="card"><div class="section-header"><div><h2>Entradas e saídas acumuladas</h2><p>Histórico registrado no módulo de estoque.</p></div></div><div class="suprimentos-table-wrap"><table class="suprimentos-table"><thead><tr><th>Produto</th><th>Entradas</th><th>Saídas</th><th>Saldo do movimento</th></tr></thead><tbody><?php foreach($entradas as $e):?><tr><td><?=h($e['nome'])?></td><td><?=nf($e['entradas'])?></td><td><?=nf($e['saidas'])?></td><td><?=nf((float)$e['entradas']-(float)$e['saidas'])?></td></tr><?php endforeach;?></tbody></table></div></div>
<div class="card"><div class="section-header"><div><h2>Histórico de preços de suprimentos</h2><p>Compare fornecedores antes de comprar.</p></div></div><div class="suprimentos-table-wrap"><table class="suprimentos-table"><thead><tr><th>Suprimento</th><th>Fornecedor</th><th>Preço unitário</th><th>Prazo</th></tr></thead><tbody><?php foreach($precos as $p):?><tr><td><?=h($p['nome'])?></td><td><?=h($p['nome_fantasia'])?></td><td>R$ <?=nf($p['preco_unitario'])?></td><td><?=h($p['prazo_entrega_dias'])?> dias</td></tr><?php endforeach;?></tbody></table></div></div>
<div class="card"><div class="section-header"><div><h2>Consumo de suprimentos — 30 dias</h2><p>Base para média diária e futura estimativa de necessidade.</p></div></div><div class="suprimentos-table-wrap"><table class="suprimentos-table"><thead><tr><th>Suprimento</th><th>Unidade</th><th>Consumo</th><th>Média diária</th></tr></thead><tbody><?php foreach($consumo as $c):?><tr><td><?=h($c['nome'])?></td><td><?=h($c['unidade_medida'])?></td><td><?=nf($c['consumo'])?></td><td><?=nf((float)$c['consumo']/30)?></td></tr><?php endforeach;?></tbody></table></div></div>
<a class="btn btn-sec" href="gestao_estoque.php?aba=visao">← Voltar ao estoque</a></div></div></div><?php include __DIR__.'/includes/footer.php'; ?>
