<?php
if(session_status()===PHP_SESSION_NONE)session_start();
require_once __DIR__.'/config/conexao.php';require_once __DIR__.'/auth/verifica_login.php';
function h($v){return htmlspecialchars((string)$v,ENT_QUOTES,'UTF-8');}
function nf($v){return number_format((float)$v,2,',','.');}
$msg=$_SESSION['uso_materiais_msg']??'';$tipo=$_SESSION['uso_materiais_tipo']??'success';unset($_SESSION['uso_materiais_msg'],$_SESSION['uso_materiais_tipo']);
$editar=null;if(isset($_GET['editar'])){$s=$pdo->prepare('SELECT * FROM consumos_materiais WHERE id=?');$s->execute([(int)$_GET['editar']]);$editar=$s->fetch()?:null;}
$materialSelecionado=(int)($_GET['material_id']??($editar['material_id']??0));
$materiais=$pdo->query("SELECT id,codigo,nome,unidade_medida,estoque_atual,estoque_minimo FROM suprimentos WHERE status='ATIVO' ORDER BY nome")->fetchAll();
$usos=$pdo->query("SELECT c.*,s.codigo,s.nome material_nome,s.unidade_medida,s.estoque_atual,s.estoque_minimo FROM consumos_materiais c JOIN suprimentos s ON s.id=c.material_id ORDER BY c.data_uso DESC,c.id DESC LIMIT 200")->fetchAll();
require_once __DIR__.'/includes/header.php';require_once __DIR__.'/includes/sidebar.php';
?>
<div class="main"><div class="topbar"><div><h1>Uso de Materiais</h1><p>Registre o consumo de materiais e acompanhe o impacto no estoque.</p></div></div><div class="content"><div class="suprimentos-container uso-materiais-page">
<?php if($msg): ?><div class="suprimentos-message <?=h($tipo==='error'?'error':'success')?>"><?=h($msg)?></div><?php endif; ?>
<div class="card uso-form-card"><div class="section-header"><div><span class="dashboard-eyebrow">MATERIAIS DE USO</span><h2><?= $editar?'Editar uso de material':'Registrar uso de material' ?></h2><p>Use esta tela quando um material for consumido na operação. A baixa será refletida imediatamente na Gestão da Loja.</p></div></div>
<form method="post" action="controllers/materiais_uso_controller.php" class="suprimentos-form-grid"><input type="hidden" name="acao" value="<?= $editar?'editar_uso':'salvar_uso' ?>"><?php if($editar): ?><input type="hidden" name="consumo_id" value="<?=h($editar['id'])?>"><?php endif; ?>
<div class="field"><label>Data do uso *</label><input type="date" name="data_uso" value="<?=h($editar['data_uso']??date('Y-m-d'))?>" required></div>
<div class="field"><label>Material de Uso *</label><select name="material_id" required><option value="">Selecione o material</option><?php foreach($materiais as $m): ?><option value="<?=h($m['id'])?>" <?=($materialSelecionado===(int)$m['id'])?'selected':''?>><?=h($m['codigo'].' — '.$m['nome'])?></option><?php endforeach; ?></select><small class="field-help">Selecione o material utilizado. O estoque disponível é considerado automaticamente.</small></div>
<div class="field"><label>Quantidade utilizada *</label><input type="number" name="quantidade" min="0.001" step="0.001" value="<?=h($editar['quantidade']??'')?>" required></div>
<div class="field full"><label>Motivo / finalidade</label><input type="text" name="motivo" maxlength="255" value="<?=h($editar['motivo']??'')?>" placeholder="Ex.: embalagem de pedidos, limpeza, expedição..."></div>
<div class="form-actions"><button class="btn btn-pri" type="submit"><?= $editar?'Salvar alteração':'Registrar uso e baixar estoque' ?></button><a class="btn btn-sec" href="gestao_loja.php?aba=materiais_uso">Voltar para Gestão da Loja</a></div></form></div>
<div class="card"><div class="section-header"><div><h2>Histórico de uso</h2><p>Cada registro reduz o estoque do material e fica disponível para auditoria.</p></div></div><div class="suprimentos-table-wrap"><table class="suprimentos-table"><thead><tr><th>Data</th><th>Material</th><th>Quantidade</th><th>Estoque atual</th><th>Motivo</th><th>Ações</th></tr></thead><tbody><?php if(!$usos): ?><tr><td colspan="6" class="empty">Nenhum uso registrado.</td></tr><?php else: foreach($usos as $u): ?><tr><td><?=h(date('d/m/Y',strtotime($u['data_uso'])))?></td><td><strong><?=h($u['material_nome'])?></strong><small><?=h($u['codigo'])?></small></td><td><?=nf($u['quantidade'])?> <?=h($u['unidade_medida']??'')?></td><td><?=nf($u['estoque_atual'])?> <small>mín.: <?=nf($u['estoque_minimo'])?></small></td><td><?=h($u['motivo']?:'—')?></td><td class="acoes"><a class="btn btn-xs btn-xs-pri" href="uso_materiais.php?editar=<?=h($u['id'])?>">Editar</a><form method="post" action="controllers/materiais_uso_controller.php" onsubmit="return confirm('Excluir este uso e devolver a quantidade ao estoque?');" style="display:inline"><input type="hidden" name="acao" value="excluir_uso"><input type="hidden" name="consumo_id" value="<?=h($u['id'])?>"><button class="btn btn-xs btn-xs-sec" type="submit">Excluir</button></form></td></tr><?php endforeach; endif; ?></tbody></table></div></div>
<div class="card"><div class="section-header"><div><h2>Como funciona</h2><p>O estoque é sensibilizado imediatamente. Se o saldo ficar próximo ou abaixo do mínimo, a Gestão da Loja passa a indicar a necessidade de reposição.</p></div></div></div>
</div></div></div>
