<?php
if(session_status()===PHP_SESSION_NONE)session_start();
require_once __DIR__.'/config/conexao.php'; require_once __DIR__.'/auth/verifica_login.php';
function h($v){return htmlspecialchars((string)$v,ENT_QUOTES,'UTF-8');} function nf($v){return number_format((float)$v,2,',','.');}
$msg=$_SESSION['venda_msg']??'';$tipo=$_SESSION['venda_tipo']??'success';unset($_SESSION['venda_msg'],$_SESSION['venda_tipo']);
$produtos=$pdo->query("SELECT p.id,p.codigo,p.sku,p.nome,p.preco_venda,COALESCE((SELECT SUM(e.quantidade) FROM estoque e WHERE e.produto_id=p.id AND e.local_estoque='FISICO'),0) estoque_local,COALESCE((SELECT SUM(e.quantidade) FROM estoque e WHERE e.produto_id=p.id AND e.local_estoque='MERCADO_LIVRE'),0) estoque_ml FROM produtos p WHERE COALESCE(p.status,'ATIVO')<>'INATIVO' ORDER BY p.nome")->fetchAll();
$vendas=$pdo->query("SELECT v.id,v.canal,v.data_venda,v.valor_total,vi.quantidade,vi.preco_unitario,p.nome item_nome,p.codigo FROM vendas v JOIN venda_itens vi ON vi.venda_id=v.id JOIN produtos p ON p.id=vi.produto_id WHERE v.status<>'CANCELADA' ORDER BY v.data_venda DESC,v.id DESC LIMIT 150")->fetchAll();
require_once __DIR__.'/includes/header.php';require_once __DIR__.'/includes/sidebar.php';
?>
<div class="main"><div class="topbar"><div><h1>Vendas</h1><p>Registre as vendas realizadas e faça a baixa automática do estoque.</p></div></div><div class="content"><div class="suprimentos-container">
<?php if($msg): ?><div class="suprimentos-message <?=h($tipo)?>"><?=h($msg)?></div><?php endif; ?>
<?php $editId=(int)($_GET['editar']??0); $editVenda=null; if($editId){$q=$pdo->prepare("SELECT v.id,v.canal,DATE(v.data_venda) data_venda,vi.produto_id,vi.quantidade,vi.preco_unitario FROM vendas v JOIN venda_itens vi ON vi.venda_id=v.id WHERE v.id=? AND v.status<>'CANCELADA' LIMIT 1");$q->execute([$editId]);$editVenda=$q->fetch()?:null;} ?>
<div class="suprimentos-form-box"><h2><?= $editVenda ? 'Editar venda' : 'Registrar venda' ?></h2><p class="form-help">A venda reduz o estoque do local correspondente ao canal escolhido.</p><form method="post" action="controllers/compras_vendas_controller.php"><input type="hidden" name="acao" value="<?= $editVenda ? 'editar_venda' : 'salvar_venda' ?>"><?php if($editVenda): ?><input type="hidden" name="venda_id" value="<?=$editVenda['id']?>"><?php endif; ?><div class="suprimentos-form-grid"><div><label>Data da venda *</label><input type="date" name="data_venda" value="<?=h($editVenda['data_venda']??date('Y-m-d'))?>" required></div><div><label>Canal *</label><select name="canal"><option value="LOCAL" <?=($editVenda['canal']??'LOCAL')==='LOCAL'?'selected':''?>>Venda local</option><option value="MERCADO_LIVRE" <?=($editVenda['canal']??'')==='MERCADO_LIVRE'?'selected':''?>>Mercado Livre</option><option value="OUTRO" <?=($editVenda['canal']??'')==='OUTRO'?'selected':''?>>Outro</option></select></div><div class="full"><label>Produto *</label><select name="produto_id" id="venda_produto" required><option value="">Selecione</option><?php foreach($produtos as $p): ?><option value="<?=$p['id']?>" data-preco="<?=$p['preco_venda']?>" data-local="<?=$p['estoque_local']?>" data-ml="<?=$p['estoque_ml']?>" <?=((int)($editVenda['produto_id']??0)===(int)$p['id'])?'selected':''?>><?=h($p['codigo'])?> — <?=h($p['nome'])?></option><?php endforeach; ?></select></div><div><label>Quantidade *</label><input type="number" name="quantidade" min="0.01" step="0.01" value="<?=h($editVenda['quantidade']??'')?>" required></div><div><label>Valor unitário *</label><input type="number" name="preco_unitario" id="venda_preco" min="0" step="0.01" value="<?=h($editVenda['preco_unitario']??'')?>" required></div></div><div class="suprimentos-info" id="venda_disponivel">Selecione um produto para visualizar o estoque disponível.</div><button class="btn btn-pri"><?= $editVenda ? 'Salvar alterações e recalcular estoque' : 'Registrar venda e baixar estoque' ?></button><?php if($editVenda): ?> <a class="btn btn-cancelar" href="vendas.php">Cancelar</a><?php endif; ?></form></div>
<div class="card"><div class="section-header"><div><h2>Histórico de vendas</h2><p>As vendas concluídas reduzem o estoque automaticamente.</p></div></div><div class="suprimentos-table-wrap"><table class="suprimentos-table"><thead><tr><th>Data</th><th>Canal</th><th>Produto</th><th>Quantidade</th><th>Valor unit.</th><th>Total</th><th>Ação</th></tr></thead><tbody><?php foreach($vendas as $v): ?><tr><td><?=date('d/m/Y',strtotime($v['data_venda']))?></td><td><?=h($v['canal']==='MERCADO_LIVRE'?'Mercado Livre':($v['canal']==='LOCAL'?'Venda local':'Outro'))?></td><td><strong><?=h($v['item_nome'])?></strong><small><?=h($v['codigo'])?></small></td><td><?=nf($v['quantidade'])?></td><td>R$ <?=nf($v['preco_unitario'])?></td><td>R$ <?=nf($v['valor_total'])?></td><td><a class="btn btn-pri" href="vendas.php?editar=<?=$v['id']?>">Editar</a> <form style="display:inline" method="post" action="controllers/compras_vendas_controller.php" onsubmit="return confirm('Excluir esta venda e devolver a quantidade ao estoque?')"><input type="hidden" name="acao" value="excluir_venda"><input type="hidden" name="venda_id" value="<?=$v['id']?>"><button class="btn btn-cancelar">Excluir</button></form></td></tr><?php endforeach; ?><?php if(!$vendas): ?><tr><td colspan="7" class="empty">Nenhuma venda registrada.</td></tr><?php endif; ?></tbody></table></div></div>
</div></div></div>
<script>(function(){const p=document.getElementById('venda_produto'),v=document.getElementById('venda_preco'),info=document.getElementById('venda_disponivel');p.addEventListener('change',function(){const o=p.options[p.selectedIndex];if(!document.querySelector('input[name=\"venda_id\"]')) v.value='';if(o&&o.value)info.textContent='Estoque local: '+o.dataset.local+' | Mercado Livre: '+o.dataset.ml;else info.textContent='Selecione um produto para visualizar o estoque disponível.';});})();</script>
<?php require_once __DIR__.'/includes/footer.php'; ?>
